format = '$all'
add_newline = false

[character] # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
success_symbol = "[>](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[status]
disabled = false

[rust]
disabled = true

[line_break]
disabled = true

[package]
disabled = false

[git_branch]
disabled = false

[git_status]
disabled = false
